trigger:
  branches:
    include:
      - main

variables:
  dockerRegistryServiceConnection: 'dockerhub-connection'
  imageRepository: 'streezie/my-app'
  tag: '$(Build.BuildId)'
stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and Push Image
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: Dockerfile
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest

- stage: Deploy_Staging
  displayName: Deploy to Staging
  dependsOn: Build
  jobs:
  - deployment: DeployStaging
    pool:
      name: 'Local-Minikube'
    environment: 'staging'
    strategy:
      runOnce:
        deploy:
          steps:
          # Pulls the K8s folder from your GitHub repo into this deployment job
          - checkout: self
          # - task: KubernetesManifest@1
          #   inputs:
          #     action: deploy
          #     kubernetesServiceConnection: 'k8s-staging-connection'
          #     namespace: staging
          #     manifests: |
          #       $(Build.SourcesDirectory)/K8s/deployment.yaml
          #     containers: |
          #       $(imageRepository):$(tag)
          - script: |
              kubectl apply -f $(Build.SourcesDirectory)/K8s/deployment.yaml -n staging
              kubectl set image deployment/my-app my-app=$(imageRepository):$(tag) -n staging
            displayName: 'Deploy to Minikube Staging'

- stage: Deploy_Production
  displayName: Deploy to Production
  dependsOn: Deploy_Staging
  jobs:
  - deployment: DeployProduction
    pool:
      name: 'Local-Minikube'
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          # Pulls the K8s folder from your GitHub repo into this deployment job
          - checkout: self
          # - task: KubernetesManifest@1
          #   inputs:
          #     action: deploy
          #     kubernetesServiceConnection: 'k8s-production-connection'
          #     namespace: production
          #     manifests: |
          #       $(Build.SourcesDirectory)/K8s/deployment.yaml
          #     containers: |
          #       $(imageRepository):$(tag)
          - script: |
              kubectl apply -f $(Build.SourcesDirectory)/K8s/deployment.yaml -n production
              kubectl set image deployment/my-app my-app=$(imageRepository):$(tag) -n production
          displayName: 'Deploy to Minikube Production'