apiVersion: v1
kind: Secret
metadata:
  name: azure-devops-sa-token
  namespace: production
  annotations:
    kubernetes.io/service-account.name: azure-devops-sa
type: kubernetes.io/service-account-token